spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: user-openapi
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/v3/api-docs
#          filters:
#            - RewritePath=/users/(?<path>.*), /$\{path}
#
#        - id: task-openapi
#          uri: lb://TASK-SERVICE
#          predicates:
#            - Path=/tasks/v3/api-docs
#          filters:
#            - RewritePath=/tasks/(?<path>.*), /$\{path}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/groups/**, /v3/api-docs

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/v1/tasks/**, /v3/api-docs

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

server:
  port: 8080

management:
  endpoint:
    gateway.enabled: true # default value
  endpoints:
    web.exposure.include: gateway

springdoc:
  swagger-ui:
    urls:
      - name: users
        url: /v3/api-docs/users
      - name: tasks
        url: /v3/api-docs/tasks
