spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**
          filters:
            - RewritePath=/tasks/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

server:
  port: 8080

springdoc:
  swagger-ui:
    urls:
      - name: users
        url: /v3/api-docs/users
      - name: tasks
        url: /v3/api-docs/tasks
