eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true