server:
  port: 7071

spring:
  application:
    name: keycloak-client
  zipkin:
    base-url: http://localhost:9411/

keycloak:
  realm: control-tower
  resource: control-tower-microservice
  auth-server-url: https://auth.saintrivers.tech/auth
  credentials:
    secret: CQpcpyUu3fdYqAazbuEqtmrkrQqibkBC

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true